// <auto-generated />
namespace Ementor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SeedM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedM));
        
        string IMigrationMetadata.Id
        {
            get { return "201511111454464_SeedM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
